FROM node:20

# Installing libvips-dev for sharp Compatability
# RUN apt-get update && apt-get install libvips-dev vim -y

RUN mkdir -p /app
WORKDIR /app

COPY package*.json yarn.lock /app/
# COPY .env /app/

# ENV PATH /app/node_modules/.bin:$PATH

# Install dependencies in /app
RUN yarn config set network-timeout 600000 -g && yarn install

# Copy the rest of our Strapi folder into /app
COPY . .

EXPOSE 1337

CMD ["yarn", "develop"]