FROM node:20

# Installing libvips-dev for sharp Compatability
# RUN apt-get update && apt-get install libvips-dev vim -y

RUN mkdir -p /usr/app
WORKDIR /usr/app

COPY package*.json yarn.lock ./

RUN yarn install

COPY . .

CMD ["yarn", "develop"]