FROM node:20

ENV PORT 3000

RUN mkdir -p /app
WORKDIR /app

COPY package*.json /app/
# COPY .env /app/

RUN yarn config set network-timeout 600000 -g && yarn install

WORKDIR /app
COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]